### ISSUE TITLE
Agreement + Department - chyby - PR13

### ISSUE THREAD

**Issue by marek5816** [MatoPavlenda/team-1-2023#18]
- [1 - ](https://github.com/MatoPavlenda/team-1-2023/pull/13/files#diff-0e4323e6a03c91c9c8dc88afef15fdad09636468c0ac3550f497618372788b6dR95) chyba autentifikacia
- [2 -](https://github.com/MatoPavlenda/team-1-2023/pull/13/files) nesedi JSON format aspon polky Response, da sa pouzit toto z [wiki](https://github.com/MatoPavlenda/team-1-2023/wiki/Standardy#error-spravy---vystupy---return)
- [3 -](https://github.com/MatoPavlenda/team-1-2023/pull/13/files#diff-0e4323e6a03c91c9c8dc88afef15fdad09636468c0ac3550f497618372788b6dR96) url ma byt s pomlckou, [wiki](https://github.com/MatoPavlenda/team-1-2023/wiki/Standardy#routes)
- [4 -](https://github.com/MatoPavlenda/team-1-2023/pull/13/files#diff-0e4323e6a03c91c9c8dc88afef15fdad09636468c0ac3550f497618372788b6dR97) do url sa nezadava ID, [wiki](https://github.com/MatoPavlenda/team-1-2023/wiki/Standardy#routes)
- [5 -](https://github.com/MatoPavlenda/team-1-2023/pull/13/files#diff-3bbc48f2d4e2bc9ce8aaf68635091f2717f68492526874ccf7ba2a6731e7dd30R22) vsade mas nastavene Required, takze clovek nedokaze editnut iba jednu hodnotu, je potrebne sometimes
- [6 -](https://github.com/MatoPavlenda/team-1-2023/pull/13/files#diff-a52d4af108bab1d4fb1fc047660237969c0da17733acca031cab52a0f356506eR23) Agreement sa neda vyhladat podla id + chyba get-all
- [7 -](https://github.com/MatoPavlenda/team-1-2023/pull/13/files#diff-f5074b50fde9e99191b911e1861e11002c2b08ccfb45d6887167a3f6c7f2a67eR22) V Agreement sa s_active vytvara a validuje ako string, teda vyznam tej premenej je trochu neznami
- [8 - ](https://github.com/MatoPavlenda/team-1-2023/pull/13/files#diff-80123b9b3b24c484ad70adca32a18827d62554155e333899de2960291dd16046R20) Agreement create dava chybu neda sa vytvorit, myslim si ze ti to bude davat chybu v vsetkych CRUD funkciach - `Base table or view not found: 1146 Table 'test.i_id_company' doesn't exist`, spravni zapis je nejako takto `exists:company,id` (pre vsetky treba upravit)
- [9 -](https://github.com/MatoPavlenda/team-1-2023/pull/13/files#diff-a52d4af108bab1d4fb1fc047660237969c0da17733acca031cab52a0f356506eR23) ?Zbehne to ked vyplnis iba niektore hodnoty, neda sa otestovat kvoli chybe 8

**Comment by marek5816** [comment]
- [10 -](https://github.com/MatoPavlenda/team-1-2023/pull/13/files#diff-0e4323e6a03c91c9c8dc88afef15fdad09636468c0ac3550f497618372788b6dR99) zle request metody na viacerych miestach, treba mat aj PATCH a DELETE

**Comment by MatoPavlenda** [comment]
všetky ISSUE hotové
