### ISSUE TITLE
Opravit routes - Zanechat komenty

### ISSUE THREAD

**Issue by marek5816** [MatoPavlenda/team-1-2023#2]
https://github.com/MatoPavlenda/team-1-2023/commit/b984b495a6a1d5971b56c516cbfc2bae6f1e3c3d#diff-0e4323e6a03c91c9c8dc88afef15fdad09636468c0ac3550f497618372788b6dR56
Tu mas vsetky routy zle, musia ti zacinat nazvom funkcie pre ktoru su urcene
Takze napr
/practice-report/create

https://github.com/MatoPavlenda/team-1-2023/commit/b984b495a6a1d5971b56c516cbfc2bae6f1e3c3d#diff-0e4323e6a03c91c9c8dc88afef15fdad09636468c0ac3550f497618372788b6dL25
Tu si zmazal komentare, tie ostavaju pre prehladnost

**Comment by SimonKazik** [comment]
Ok, routy som prepísal a komentáre naspäť pridal.

**Comment by marek5816** [comment]
https://github.com/MatoPavlenda/team-1-2023/commit/8884388c7d862930da3af9741968a1ced04badaa - tu opravene

pisal som aj na discord pridavajte odkaz na komiti
