### ISSUE TITLE
Company Review - Chyba bodovanie + Validacia Studenta - PR21

### ISSUE THREAD

**Issue by marek5816** [MatoPavlenda/team-1-2023#22]
- [1 - ](https://github.com/MatoPavlenda/team-1-2023/pull/21/files#diff-56bd7c3d5a7b477aa1be684828be00d12b8cd7fb1392879ecffd8ae8840a97a3R15) Chyba bodove hodnotenie spolocnosti 1-10, summary
- [2 - ](https://github.com/MatoPavlenda/team-1-2023/pull/21/files#diff-80181d9aeabb4b9c431231f548e83c235e5df2140310f549eb004acc1700c745R68) Chyba validacia ci student edituje svoj review + dodatocne bude treba zmenit required na sometimes ked sa prida bodove hodnotenie

**Comment by Fmladek** [comment]
Done, in this [pull](https://github.com/MatoPavlenda/team-1-2023/pull/26/files)
